#ifndef DEV_PCI_H
#define DEV_PCI_H

#define PCI_CLASS_UNCLASSIFIED 0x0
#define PCI_CLASS_MASS_STORAGE 0x1
#define PCI_CLASS_NETWORK      0x2
#define PCI_CLASS_DISPLAY      0x3
#define PCI_CLASS_MULTIMEDIA   0x4
#define PCI_CLASS_MEMORY       0x5
#define PCI_CLASS_BRIDGE       0x6
#define PCI_CLASS_SIMPLE_COM   0x7
#define PCI_CLASS_BASE_SYSTEM  0x8
#define PCI_CLASS_INPUT_DEVICE 0x9
#define PCI_CLASS_DOCKING      0xA
#define PCI_CLASS_PROCESSOR    0xB
#define PCI_CLASS_SERIAL_BUS   0xC
#define PCI_CLASS_WIRELESS     0xD
#define PCI_CLASS_INTELLIGENT  0xE
#define PCI_CLASS_SATELLITE    0xF
#define PCI_CLASS_ENCRYPTION   0x10
#define PCI_CLASS_SIGNAL       0x11
#define PCI_CLASS_ACCELERATOR  0x12

#define PCI_SUBCLASS_UNCLASSIFIED_NONVGA 0x0
#define PCI_SUBCLASS_UNCLASSIFIED_VGA    0x1

#define PCI_SUBCLASS_MASS_STORAGE_SCSI   0x0
#define PCI_SUBCLASS_MASS_STORAGE_IDE    0x1
#define PCI_SUBCLASS_MASS_STORAGE_FLOPPY 0x2
#define PCI_SUBCLASS_MASS_STORAGE_IPI    0x3
#define PCI_SUBCLASS_MASS_STORAGE_RAID   0x4
#define PCI_SUBCLASS_MASS_STORAGE_ATA    0x5
#define PCI_SUBCLASS_MASS_STORAGE_SATA   0x6
#define PCI_SUBCLASS_MASS_STORAGE_SAS    0x7
#define PCI_SUBCLASS_MASS_STORAGE_NVM    0x8

#define PCI_SUBCLASS_NETWORK_ETHERNET   0x0
#define PCI_SUBCLASS_NETWORK_TOKENRING  0x1
#define PCI_SUBCLASS_NETWORK_FDDI       0x2
#define PCI_SUBCLASS_NETWORK_ATM        0x3
#define PCI_SUBCLASS_NETWORK_ISDN       0x4
#define PCI_SUBCLASS_NETWORK_WORLDFIP   0x5
#define PCI_SUBCLASS_NETWORK_PICMG      0x6
#define PCI_SUBCLASS_NETWORK_INFINIBAND 0x7
#define PCI_SUBCLASS_NETWORK_FABRIC     0x8

#define PCI_SUBCLASS_DISPLAY_VGA 0x0
#define PCI_SUBCLASS_DISPLAY_XGA 0x1
#define PCI_SUBCLASS_DISPLAY_3D  0x2

#define PCI_SUBCLASS_MULTIMEDIA_VIDEO     0x0
#define PCI_SUBCLASS_MULTIMEDIA_AUDIO     0x1
#define PCI_SUBCLASS_MULTIMEDIA_TELEPHONE 0x2
#define PCI_SUBCLASS_MULTIMEDIA_AUDIODEV  0x3

#define PCI_SUBCLASS_MEMORY_RAM   0x0
#define PCI_SUBCLASS_MEMORY_FLASH 0x1

#define PCI_SUBCLASS_BRIDGE_HOST       0x0
#define PCI_SUBCLASS_BRIDGE_ISA        0x1
#define PCI_SUBCLASS_BRIDGE_EISA       0x2
#define PCI_SUBCLASS_BRIDGE_MCA        0x3
#define PCI_SUBCLASS_BRIDGE_PCI        0x4
#define PCI_SUBCLASS_BRIDGE_PCMCIA     0x5
#define PCI_SUBCLASS_BRIDGE_NUBUS      0x6
#define PCI_SUBCLASS_BRIDGE_CARDBUS    0x7
#define PCI_SUBCLASS_BRIDGE_RACEWAY    0x8
#define PCI_SUBCLASS_BRIDGE_PCI2       0x9
#define PCI_SUBCLASS_BRIDGE_INFINIBAND 0xA

void pci_init(void);

#endif
