BIN = libc.so

SRC = string.c \
      ctype.c \
      stdlib.c \
      printf.c \
      syscall.c \
      syscall.s \
      malloc.c \
      stdio.c \
      dirent.c \
      getopt.c \

include $(MKDIR)/lib.mk
